package test;

import static org.junit.jupiter.api.Assertions.fail;

/*
public class ExceptionTest {

    ScannerOperations pr;
    Scanner scanner;

    @BeforeEach
    public void Setup(){
        pr = new ScannerOperations();
        scanner = new Scanner(System.in);
    }

    @Test
    public void testWrongInputThrows() throws IOException {
        try {
            pr.runScanner();
            scanner.next("Don't do that!");
            fail("I was not expecting to reach this line of code");
        } catch (NotCorrectEntryException e) {
            System.out.println("Great!");
        }
    }

    @Test
    public void testWrongInputDoesNotThrow() throws IOException{
        try {
            pr.runScanner();
            scanner.next("Add a driver");
        } catch (NotCorrectEntryException e) {
            fail("I was not expecting NotCorrectEntryException");
        }
    }

    @Test
    public void testWrongInputThrows2() throws IOException {
        try {
            pr.AddMember();
            fail("I was not expecting to reach this line of code");
        } catch (NotCorrectEntryException e) {
            System.out.println("Great!");
        }
    }

    @Test
    public void testWrongInputDoesNotThrow2() throws IOException{
        try {
            pr.AddMember();
        } catch (NotCorrectEntryException e) {
            fail("I was not expecting NotCorrectEntryException");
        }
    }
}*/
